# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mixer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.frame_12)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.showcomp1 = QtWidgets.QComboBox(self.frame_2)
        self.showcomp1.setMinimumSize(QtCore.QSize(181, 21))
        self.showcomp1.setMaximumSize(QtCore.QSize(200, 21))
        self.showcomp1.setObjectName("showcomp1")
        self.showcomp1.addItem("")
        self.showcomp1.addItem("")
        self.showcomp1.addItem("")
        self.showcomp1.addItem("")
        self.showcomp1.addItem("")
        self.horizontalLayout_3.addWidget(self.showcomp1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_12)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.widImg1 = ImageView(self.frame)
        self.widImg1.setMinimumSize(QtCore.QSize(168, 171))
        self.widImg1.setObjectName("widImg1")
        self.widImg1.ui.histogram.hide()
        self.widImg1.ui.roiBtn.hide()
        self.widImg1.ui.menuBtn.hide()
        self.widImg1.ui.roiPlot.hide()
        self.widImg1.getView().setAspectLocked(False)
        self.widImg1.view.setAspectLocked(False)
        self.gridLayout.addWidget(self.widImg1, 0, 0, 1, 1)
        self.widcomp1 = ImageView(self.frame)
        self.widcomp1.setMinimumSize(QtCore.QSize(167, 171))
        self.widcomp1.setObjectName("widcomp1")
        self.widcomp1.ui.histogram.hide()
        self.widcomp1.ui.roiBtn.hide()
        self.widcomp1.ui.menuBtn.hide()
        self.widcomp1.ui.roiPlot.hide()
        self.widcomp1.getView().setAspectLocked(False)
        self.widcomp1.view.setAspectLocked(False)
        self.gridLayout.addWidget(self.widcomp1, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame)
        self.gridLayout_13.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_14)
        self.label_2.setMaximumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.showcomp2 = QtWidgets.QComboBox(self.frame_14)
        self.showcomp2.setMinimumSize(QtCore.QSize(181, 21))
        self.showcomp2.setMaximumSize(QtCore.QSize(200, 21))
        self.showcomp2.setObjectName("showcomp2")
        self.showcomp2.addItem("")
        self.showcomp2.addItem("")
        self.showcomp2.addItem("")
        self.showcomp2.addItem("")
        self.showcomp2.addItem("")
        self.horizontalLayout_4.addWidget(self.showcomp2)
        self.gridLayout_15.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widImg2 = ImageView(self.frame_15)
        self.widImg2.setMinimumSize(QtCore.QSize(168, 171))
        self.widImg2.setObjectName("widImg2")
        self.widImg2.ui.histogram.hide()
        self.widImg2.ui.roiBtn.hide()
        self.widImg2.ui.menuBtn.hide()
        self.widImg2.ui.roiPlot.hide()
        self.widImg2.getView().setAspectLocked(False)
        self.widImg2.view.setAspectLocked(False)
        self.gridLayout_16.addWidget(self.widImg2, 0, 0, 1, 1)
        self.widcomp2 = ImageView(self.frame_15)
        self.widcomp2.setMinimumSize(QtCore.QSize(167, 171))
        self.widcomp2.setObjectName("widcomp2")
        self.widcomp2.ui.histogram.hide()
        self.widcomp2.ui.roiBtn.hide()
        self.widcomp2.ui.menuBtn.hide()
        self.widcomp2.ui.roiPlot.hide()
        self.widcomp2.getView().setAspectLocked(False)
        self.widcomp2.view.setAspectLocked(False)
        self.gridLayout_16.addWidget(self.widcomp2, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_15)
        self.gridLayout_14.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_11)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.slider1 = QtWidgets.QSlider(self.frame_7)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.slider1.setMaximumSize(QtCore.QSize(150, 22))
        self.gridLayout_7.addWidget(self.slider1, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chooseimg1 = QtWidgets.QComboBox(self.frame_7)
        self.chooseimg1.setMinimumSize(QtCore.QSize(116, 20))
        self.chooseimg1.setObjectName("chooseimg1")
        self.chooseimg1.addItem("")
        self.chooseimg1.addItem("")
        self.verticalLayout_3.addWidget(self.chooseimg1)
        self.choosecomp1 = QtWidgets.QComboBox(self.frame_7)
        self.choosecomp1.setMinimumSize(QtCore.QSize(116, 20))
        self.choosecomp1.setObjectName("choosecomp1")
        self.choosecomp1.addItem("")
        self.choosecomp1.addItem("")
        self.choosecomp1.addItem("")
        self.choosecomp1.addItem("")
        self.choosecomp1.addItem("")
        self.choosecomp1.addItem("")
        self.choosecomp1.addItem("")
        self.choosecomp1.setMaximumSize(QtCore.QSize(150, 20))
        self.verticalLayout_3.addWidget(self.choosecomp1)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_11)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 130))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chooseimg2 = QtWidgets.QComboBox(self.frame_6)
        self.chooseimg2.setMinimumSize(QtCore.QSize(116, 20))
        self.chooseimg2.setObjectName("chooseimg2")
        self.chooseimg2.addItem("")
        self.chooseimg2.addItem("")
        self.verticalLayout_2.addWidget(self.chooseimg2)
        self.choosecomp2 = QtWidgets.QComboBox(self.frame_6)
        self.choosecomp2.setMinimumSize(QtCore.QSize(116, 20))
        self.choosecomp2.setObjectName("choosecomp2")
        self.choosecomp2.addItem("")
        self.choosecomp2.setMaximumSize(QtCore.QSize(150, 20))
        self.verticalLayout_2.addWidget(self.choosecomp2)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.slider2 = QtWidgets.QSlider(self.frame_6)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.slider2.setMaximumSize(QtCore.QSize(150, 22))
        self.gridLayout_6.addWidget(self.slider2, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.gridLayout_11.addLayout(self.verticalLayout_5, 2, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_11)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_11)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_11)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 110))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.gridLayout_11.addLayout(self.verticalLayout_4, 0, 0, 3, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setMinimumSize(QtCore.QSize(49, 20))
        self.label_5.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setMaximumSize(QtCore.QSize(52, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.chooseOut = QtWidgets.QComboBox(self.frame_4)
        self.chooseOut.setMinimumSize(QtCore.QSize(100, 20))
        self.chooseOut.setObjectName("chooseOut")
        self.chooseOut.addItem("")
        self.chooseOut.addItem("")
        self.horizontalLayout_2.addWidget(self.chooseOut)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgOut = ImageView(self.frame_3)
        self.widgOut.setMinimumSize(QtCore.QSize(162, 159))
        self.widgOut.setObjectName("widgOut")
        self.widgOut.ui.histogram.hide()
        self.widgOut.ui.roiBtn.hide()
        self.widgOut.ui.menuBtn.hide()
        self.widgOut.ui.roiPlot.hide()
        self.widgOut.getView().setAspectLocked(False)
        self.widgOut.view.setAspectLocked(False)
        self.horizontalLayout.addWidget(self.widgOut)
        self.widgOut2 = ImageView(self.frame_3)
        self.widgOut2.setMinimumSize(QtCore.QSize(161, 159))
        self.widgOut2.setObjectName("widgOut2")
        self.widgOut2.ui.histogram.hide()
        self.widgOut2.ui.roiBtn.hide()
        self.widgOut2.ui.menuBtn.hide()
        self.widgOut2.ui.roiPlot.hide()
        self.widgOut2.getView().setAspectLocked(False)
        self.widgOut2.view.setAspectLocked(False)
        self.horizontalLayout.addWidget(self.widgOut2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.gridLayout_17.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.upload = QtWidgets.QAction(MainWindow)
        self.upload.setObjectName("upload")
        self.actionUpload_image_2 = QtWidgets.QAction(MainWindow)
        self.actionUpload_image_2.setObjectName("actionUpload_image_2")
        self.menuFile.addAction(self.upload)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.showcomp1.setCurrentIndex(0)
        self.showcomp2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Image 1"))
        self.showcomp1.setItemText(0, _translate("MainWindow", "Select  Component"))
        self.showcomp1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.showcomp1.setItemText(2, _translate("MainWindow", "Phase"))
        self.showcomp1.setItemText(3, _translate("MainWindow", "Real"))
        self.showcomp1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.label_2.setText(_translate("MainWindow", "Image 2"))
        self.showcomp2.setItemText(0, _translate("MainWindow", "Select  Component"))
        self.showcomp2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.showcomp2.setItemText(2, _translate("MainWindow", "Phase"))
        self.showcomp2.setItemText(3, _translate("MainWindow", "Real"))
        self.showcomp2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.chooseimg1.setItemText(0, _translate("MainWindow", "Image 1"))
        self.chooseimg1.setItemText(1, _translate("MainWindow", "Image 2"))
        self.choosecomp1.setItemText(0, _translate("MainWindow", "Select"))
        self.choosecomp1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.choosecomp1.setItemText(2, _translate("MainWindow", "Phase"))
        self.choosecomp1.setItemText(3, _translate("MainWindow", "Real"))
        self.choosecomp1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.choosecomp1.setItemText(5, _translate("MainWindow", "Uniform Magnitude"))
        self.choosecomp1.setItemText(6, _translate("MainWindow", "Uniform Phase"))
        self.choosecomp2.setItemText(0, _translate("MainWindow", "Select Component 1"))
        self.chooseimg2.setItemText(0, _translate("MainWindow", "Image 1"))
        self.chooseimg2.setItemText(1, _translate("MainWindow", "Image 2"))
        self.label_3.setText(_translate("MainWindow", "Mixer"))
        self.label_4.setText(_translate("MainWindow", "Component 1"))
        self.label_7.setText(_translate("MainWindow", "Component 2"))
        self.label_5.setText(_translate("MainWindow", "Output 1"))
        self.label_6.setText(_translate("MainWindow", "Output 2"))
        self.chooseOut.setItemText(0, _translate("MainWindow", "Output 1"))
        self.chooseOut.setItemText(1, _translate("MainWindow", "Output 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.upload.setText(_translate("MainWindow", "Upload "))
        self.actionUpload_image_2.setText(_translate("MainWindow", "Upload image 2"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
